### ISSUE TITLE
Nether Analytics Scheduler

### ISSUE THREAD

**Issue by krist00fer** [MicrosoftDX/nether#472]
## Updated the thoughts on this issue can be found further down the discussion thread ##
(This initial comment is kept for history)

Implement "simple" scheduler that allows you to write code similar to below example.

```CSharp
var blobSynchronizer = new BlobLeaseSynchronizer("...")
var builder = new SchedulerBuilder();

builder.Schedule("clustering")
    .Every(TimeSpan.FromHour(1))
    .CatchUpMissedOpportunities(true)
    .SynchronizeUsing(blobSynchronizer)
    .RunJob(...)
    .RunJob(...)
    .ReadAndOutput(...)

var jobPipelineBuilder = new JobPipelineBuilder()

```

**Comment by dgkanatsios** [comment]
So, I've been thinking about the scheduler and here's my draft implementation plan. Assuming that we have jobs called job1, job2 etc that may correspond to U-SQL Scripts. These jobs can be scheduler to run either every 15', 30' or 60'.

The backing implementation could possibly utilize Table Storage with the following schema

| PartitionKey | RowKey | DateTimeOfJob | DateTimeStarted | Status | Log |
|--------------|--------|---------------|-----------------|--------|-----|

- **PartitionKey**: Name of the job (job1) concatenated with time interval(e.g. job1-15, job2-30 etc.). We need to concatenate with time interval since we may need a job to run at different intervals
- **RowKey**: this will be DateTime.MaxValue.Ticks - DateTime.Now.Ticks. Table Storage orders entities by PartitionKey and RowKey. If we use this value for the RowKey, this will allow us to do a LINQ Take(1) and get the last time this kind of job was executed. PrimaryKey and RowKey combination can serve as the 'primary key' for the entity
- **DateTimeOfJob**: this will be of the format yyyyMMdd-HHmm This is a format that can easily be parsed by DateTime.Parse and will hold the value of the time of the job (e.g. for two consecutive jobs that need to run (second job to run after 15') this will be 20170523-2000 and 20170523-2015)
- **DateTimeStarted**: the actual datetime that job started - for logging purposes
- **Status**: the current status of the job (running, stopped, fault etc.)
- **Log**: just a string with debug info

 So, algorithm could work like this

- on first execution, user opts to schedule job1 to run every 15', job2 to run every 30'
- job1 and job2 are kept in an internal list, the below steps run in a loop for each job
- check table storage, regarding the current job and its interval (i.e.check PartitionKey), use Take(1) so that we get the last executed job
  - if there are no entries (e.g. first time execution)
    - create an entry in table storage taking into account a) current dateTime and b) interval. For example, if we need to run job1 every 15' and current time is 20:33, we will create a DateTimeOfJob as 20170523-2030 (20:30 will be the first execution time)
    - pass the job to the jobExecutor so it can execute it (described below)
  - if there are entries in Table Storage about this job, check the DateTimeOfJob of the last executing job. Since we applied ordering via Ticks (see above), by doing Take(1) for specified PartionKey and RowKey we will get the time of the last executing job
  - find the missed opportunities! For example, suppose that we had issued job1 to run every 30'. Last executed job (DateTimeOfJob) was 20170523-1830. Time now is 20:18, so we will send the following jobs to the jobExecutor
    - 20170523-1900
    - 20170523-1930
    - 20170523-2000
  - add these jobs as entries to the table storage
 - loop for remaining jobs
 - Task.Delay and then loop again for all jobs on the internal list

**jobExecutor**
The jobExecutor object gets a Job object that contains PartitionKey, RowKey. It runs the job via a Task and then updates its status on the Table Storage. 
  
**Potential pitfalls**
What happens if a job fails? This is not handled by the above scenario. Moreover, to discover failed jobs on the Table Storage would require a table scan, since the status is not part of PartitionKey and RowKey columns.

**Comment by krist00fer** [comment]
@dgkanatsios I'd love if we could see some sample code around this. What I'm thinking is something along these lines (just out of my head and perhaps not with all details)

I'm using my own naming in this example so don't confuse it with the naming of classes that you've used above.

```cs
var stateProvider = new BlobStorageStateProvider();  // Responsible for state
var everyHourOnTheHour = new EveryHourOnTheHourSchedule(stateProvider);
var syncProvider = new BlobSynchronizationProvider(); // Responsible for Singleton Implementation
var jobExecutor = new JobExecutor(syncProvider);

while (true)
{
    var job1 = jobExecutor.RunAsSingletonAsync("job1", everyHourOnTheHour, async (d) => 
    {
        // variable d is of type DateTime and is set to the date and time when the job
        // was supposed to have run, i.e. on the hour of whatever hour we should have run on

        var jobManager = new DataLakeAnalyticsJobManager():

        // Set parameters and others here

        await jobManager.SubmitJobAsync(...);
    });

    // Add more jobs here

    Task.WaitAll(job1, job2, job3, ...);

    await Task.Delay(TimeSpan.FromMinutes(5));
}

```

By doing something like this we break apart the problem into several smaller things:

1. What schedule am I following, the Schedule Class
2.  and have I executed according to that schedule, the StateProvider Class
3. Am I the only one trying to run job X using this schedule, the SyncProvider Class
4. How do I put it all together, the jobExecutor
5. And finally, what to do at this schedule? That is the C# code in the anonymous method

Let me know what you think about this approach. I know it's somewhat different to yours, but let's discuss pros and cons.

**Comment by krist00fer** [comment]
The way the code above is proposed, it'll work great if you put it in another scheduling mechanism as well, such as Azure Functions or just a regular at-command in the terminal window
